'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8762
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("cced64f9-a5f2-4665-9e4b-5727beb2675b")> 

'Original file name:
'Generation date: 2/10/2018 3:23:43 PM
'''<summary>
'''There are no comments for COHORTDBEntities in the schema.
'''</summary>
Partial Public Class COHORTDBEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new COHORTDBEntities object using the connection string found in the 'COHORTDBEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=COHORTDBEntities", "COHORTDBEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new COHORTDBEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "COHORTDBEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new COHORTDBEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "COHORTDBEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for tblUserDetails in the schema.
    '''</summary>
    Public ReadOnly Property tblUserDetails() As Global.System.Data.Objects.ObjectQuery(Of tblUserDetails)
        Get
            If (Me._tblUserDetails Is Nothing) Then
                Me._tblUserDetails = MyBase.CreateQuery(Of tblUserDetails)("[tblUserDetails]")
            End If
            Return Me._tblUserDetails
        End Get
    End Property
    Private _tblUserDetails As Global.System.Data.Objects.ObjectQuery(Of tblUserDetails)
    '''<summary>
    '''There are no comments for tblUserDetails in the schema.
    '''</summary>
    Public Sub AddTotblUserDetails(ByVal tblUserDetails As tblUserDetails)
        MyBase.AddObject("tblUserDetails", tblUserDetails)
    End Sub
End Class
'''<summary>
'''There are no comments for COHORTDBModel.tblUserDetails in the schema.
'''</summary>
'''<KeyProperties>
'''UserID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="COHORTDBModel", Name:="tblUserDetails"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class tblUserDetails
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new tblUserDetails object.
    '''</summary>
    '''<param name="userID">Initial value of UserID.</param>
    Public Shared Function CreatetblUserDetails(ByVal userID As Integer) As tblUserDetails
        Dim tblUserDetails As tblUserDetails = New tblUserDetails
        tblUserDetails.UserID = userID
        Return tblUserDetails
    End Function
    '''<summary>
    '''There are no comments for Property UserID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property UserID() As Integer
        Get
            Return Me._UserID
        End Get
        Set
            Me.OnUserIDChanging(value)
            Me.ReportPropertyChanging("UserID")
            Me._UserID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("UserID")
            Me.OnUserIDChanged
        End Set
    End Property
    Private _UserID As Integer
    Partial Private Sub OnUserIDChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnUserIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property DeptID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property DeptID() As Global.System.Nullable(Of Integer)
        Get
            Return Me._DeptID
        End Get
        Set
            Me.OnDeptIDChanging(value)
            Me.ReportPropertyChanging("DeptID")
            Me._DeptID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("DeptID")
            Me.OnDeptIDChanged
        End Set
    End Property
    Private _DeptID As Global.System.Nullable(Of Integer)
    Partial Private Sub OnDeptIDChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
    Partial Private Sub OnDeptIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property LastName in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property LastName() As String
        Get
            Return Me._LastName
        End Get
        Set
            Me.OnLastNameChanging(value)
            Me.ReportPropertyChanging("LastName")
            Me._LastName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("LastName")
            Me.OnLastNameChanged
        End Set
    End Property
    Private _LastName As String
    Partial Private Sub OnLastNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnLastNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property FirstName in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property FirstName() As String
        Get
            Return Me._FirstName
        End Get
        Set
            Me.OnFirstNameChanging(value)
            Me.ReportPropertyChanging("FirstName")
            Me._FirstName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("FirstName")
            Me.OnFirstNameChanged
        End Set
    End Property
    Private _FirstName As String
    Partial Private Sub OnFirstNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnFirstNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property MiddleName in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property MiddleName() As String
        Get
            Return Me._MiddleName
        End Get
        Set
            Me.OnMiddleNameChanging(value)
            Me.ReportPropertyChanging("MiddleName")
            Me._MiddleName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("MiddleName")
            Me.OnMiddleNameChanged
        End Set
    End Property
    Private _MiddleName As String
    Partial Private Sub OnMiddleNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnMiddleNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property EmailAddress in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property EmailAddress() As String
        Get
            Return Me._EmailAddress
        End Get
        Set
            Me.OnEmailAddressChanging(value)
            Me.ReportPropertyChanging("EmailAddress")
            Me._EmailAddress = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("EmailAddress")
            Me.OnEmailAddressChanged
        End Set
    End Property
    Private _EmailAddress As String
    Partial Private Sub OnEmailAddressChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnEmailAddressChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property UserName in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property UserName() As String
        Get
            Return Me._UserName
        End Get
        Set
            Me.OnUserNameChanging(value)
            Me.ReportPropertyChanging("UserName")
            Me._UserName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("UserName")
            Me.OnUserNameChanged
        End Set
    End Property
    Private _UserName As String
    Partial Private Sub OnUserNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnUserNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Password in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Password() As String
        Get
            Return Me._Password
        End Get
        Set
            Me.OnPasswordChanging(value)
            Me.ReportPropertyChanging("Password")
            Me._Password = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Password")
            Me.OnPasswordChanged
        End Set
    End Property
    Private _Password As String
    Partial Private Sub OnPasswordChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnPasswordChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Gender in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Gender() As String
        Get
            Return Me._Gender
        End Get
        Set
            Me.OnGenderChanging(value)
            Me.ReportPropertyChanging("Gender")
            Me._Gender = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Gender")
            Me.OnGenderChanged
        End Set
    End Property
    Private _Gender As String
    Partial Private Sub OnGenderChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnGenderChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Position in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Position() As String
        Get
            Return Me._Position
        End Get
        Set
            Me.OnPositionChanging(value)
            Me.ReportPropertyChanging("Position")
            Me._Position = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Position")
            Me.OnPositionChanged
        End Set
    End Property
    Private _Position As String
    Partial Private Sub OnPositionChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnPositionChanged()
        End Sub
End Class
